language: ruby
rvm:
- 2.4.1


# install jekyll from gemfile and build
install: 
   - bundle install

   - rake
   - chmod +x ./scripts/build.sh
   - ./scripts/build.sh


scripts: true

# deploy to surge.sh
after_success: 
   - npm install --global surge
   - surge --project ./_site

# branch whitelist, only for GitHub Pages
#branches:
#  only:
#  - master


cache: bundler
notifications:
  email: false
