title:              Il Regno della Sintassi
email:              hiemsword08+rsintassi@pm.me
description:        Benvenuto nel mio Regno! Qui puoi vedere i miei blog sintassiosi
author:             Re della Sintassi
baseurl:            ""
url:                "hiemsword.github.io"

# Social Profiles
twitter_username:   RSintassi
github_username:    StartBootstrap
facebook_username:  StartBootstrap
instagram_username:  
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
