name: Jekyll site CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Build Jekyll
      uses: jerryjvl/jekyll-build-action@v1
      
    - name: Deploy to regnodellasintassi.surge.sh
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: 'regnodellasintassi.surge.sh'
        project: '/github/workspace/_site'
        login: ${{ secrets.surge_login }}
        token: ${{ secrets.surge_token }}
