name: Surge site CI

on:
  workflow_dispatch:
  push:
    branches: [ master ]

jobs:
  build:
    name: Surge site build
    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Deploy to regnodellasintassi.surge.sh
      uses: dswistowski/surge-sh-action@v1
      with:
        domain: 'regnodellasintassi.surge.sh'
        project: './_site'
        login: ${{ secrets.surge_login }}
        token: ${{ secrets.surge_token }}

