# This is a basic workflow that is manually triggered

name: Manual Site build&upload

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Artifact name'
        # Default value if no value is explicitly provided
        default: '_site'
        # Input has to be provided for the workflow to run
        required: false

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Build Jekyll
      uses: jerryjvl/jekyll-build-action@v1

    - name: Upload Jekyll build
      uses: actions/upload-artifact@v2
      with:
        name: ${{ github.event.inputs.name }}"
        path: ./_site # or path/to/artifact
